TRUTH = (
    "¿Has ignorado a alguien?"
    "¿Alguna vez has visto a tus padres haciéndolo?",
    "¿Quién fue la última persona que te gustó? ¿Por qué?",
    "¿Alguna vez te han suspendido de la escuela?",
    "Si tuvieras que elegir entre ir desnudo o que tus pensamientos aparecieran en burbujas sobre tu cabeza para que todos pudieran leer, ¿cuál elegirías?",
    "¿Qué es lo único que temes perder?",
    "¿Te gusta alguien en este momento?",
    "¿Una cosa de tu mejor amigo de la que estás celoso?",
    "¿Engañarías a tu novio por un chico rico?",
    "¿Cuál es tu mayor excitación?",
    "¿Cuándo fue la última vez que mentiste a sus padres y por qué?",
    "Describe a tu pareja ideal",
    "¿Qué es lo más aterrador que has hecho?",
    "¿Alguna vez te has picado la nariz y comido eso?",
    "¿Cuándo fue la última vez que les mintió a sus padres y por qué?",
    "¿Alguna vez ha mentido sobre tu edad para participar en un concurso?",
    "¿Alguna vez te han sorprendido mirando a alguien?"
  
)

DARE = (
    "Muestra la foto más vergonzosa en tu teléfono"
    "Muestra las últimas cinco personas a las que enviaste mensajes de texto y lo que decían los mensajes",
    "Deja que el resto del grupo envíe un mensaje de texto a alguien desde tu cuenta de Instagram",
    "Come un trozo de ajo crudo",
    "Haz 100 sentadillas",
    "Manten tres cubitos de hielo en la boca hasta que se derrita",
    "Dile algo sucio a la persona que escribio abajo",
    "Pon 10 diferentes líquidos disponibles en una taza y bébela",
    "Grita la primera palabra que te venga a la mente",
    "Grabate haciendo un baile erótico y envialo a alguien de tu elección",
    "Quitate cuatro prendas y envia la evidencia al chat",
    "Dale me gusta en las primeras 15 publicaciones de tu suministro de noticias de Facebook",
    "Come una cucharada de mostaza",
    "Envía un mensaje de texto a la última persona de tu directorio telefónico",
    "Muestra tu cara de orgasmo",
    "Come seductoramente un plátano",
    "Vacia tu billetera / bolso y muestre a todos lo que hay dentro",
    "Haz tu mejor pose sexy",
    "Finge ser parte de otro fandom en tw durante 10 minutos",
    "Come un bocadillo sin usar las manos",
    "Di dos cosas honestas sobre todos los demás en el grupo",
    "Intenta meterte todo el puño en la boca",
    "Cuéntales a todos una historia vergonzosa sobre ti",
    "Intenta lamerte el codo",
    "Publica la selfie más antigua en tu teléfono en las Historias de Instagram",
    "Cuenta la historia más triste que conozcas",
    "Ponga en su boca tantos bocadillos a la vez como pueda",
    "Envía tu selfie más reciente",
    "Envía tu selfie más feo",
    "Envia un screenshot de tu historial de facebook",
    "Envia un screenshot de tu galeria.",
    "Envia un screenshot de tu buzon de entrada",
    "Di algo muy íntimo",
    "Envía una screenshot de tu bandeja de entrada de Twitter",
    "Envía una screenshot de tu pantalla de inicio",
    "Envía una audio cantando de tu canción favorita 🎤",
    "Confiesa tu amor actual. ❤️",
    "Declara quién es tu verdadero amor",
    "El mensaje de abajo elige tu siguiente foto de perfil",
    "Envia mas retos a mis creador @luisx_garcia",
)
